import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KPI-ONEPAGE",
  description: "Generated by กลุ่มงานสุขภาพดิจิทัล",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="border-t border-slate-200 bg-white/80 px-6 py-4 text-center text-xs text-slate-600">
          <div>Copyright © 2026 by สุพจน์ สุดสี.</div>
          <div>All Rights Reserved.</div>
          <div>กลุ่มงานสุขภาพดิจิท้ล สำนักงานสาธารณสุขจังหวัดอุบลราชธานี</div>
        </footer>
      </body>
    </html>
  );
}
